name = "fetcher"
main = "src/index.ts"
compatibility_date = "2024-01-14"

[[r2_buckets]]
binding = "R2_BUCKET_WEUR"
bucket_name = "<ignored>"
preview_bucket_name = "objects_weur"

[[r2_buckets]]
binding = "R2_BUCKET_WNAM"
bucket_name = "<ignored>"
preview_bucket_name = "objects_wnam"

[[r2_buckets]]
binding = "R2_BUCKET_APAC"
bucket_name = "<ignored>"
preview_bucket_name = "objects_apac"

[[kv_namespaces]]
binding = "ASSETS_KV"
id = "<ignored>"
preview_id = "assets"
