name = "fetcher"
main = "src/index.ts"
compatibility_date = "2024-01-14"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "<ignored>"
preview_bucket_name = "objects"

[[kv_namespaces]]
binding = "ASSETS_KV"
id = "<ignored>"
preview_id = "assets"
